apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: words-db
  namespace: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: tcp
  selector:
    app: words-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: words-db
  namespace: database
spec:
  template:
    metadata:
      labels:
        app: words-db
    spec:
      containers:
      - name: db
        image: dockersamples/k8s-wordsmith-db
        ports:
        - containerPort: 5432
          name: db
---
apiVersion: v1
kind: Service
metadata:
  name: words
  namespace: api
  labels:
    app: words
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: words    
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: words
  namespace: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: words
        version: v1
    spec:
      containers:
      - name: words
        image: gcr.io/your-gcp-proyect/words:latest
        ports:
        - containerPort: 8080
          name: api
---          
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: words-v2
  namespace: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: words
        version: v2
    spec:
      containers:
      - name: words
        image: gcr.io/your-project/words-v2:latest
        ports:
        - containerPort: 8080
          name: api
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: words-web
  namespace: web
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: http
  selector:
    app: words-web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: words-web
  namespace: web
spec:
  template:
    metadata:
      labels:
        app: words-web
    spec:
      containers:
      - name: web
        image: gcr.io/your-project/front:latest
        ports:
        - containerPort: 80
          name: words-web
